name: Run Scraping Process

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
          COOKIES_B64: ${{ secrets.COOKIES_B64 }}
          EMAIL: ${{ secrets.EMAIL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Restore cookies
        run: |
          mkdir -p users
          echo "$COOKIES_B64" | base64 --decode > "users/${EMAIL}.pkl"
      
      - name: Init scraper
        run: python example.py
      
      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: csv-files
          path: data/raw_data/*.csv
