name: Run Scraping Process

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Restore cookies
        run: |
          mkdir -p users
          cd users
          echo "$COOKIES_B64" | base64 --decode > "${EMAIL}.pkl"
        env:
          COOKIES_B64: ${{ secrets.COOKIES_B64 }}
          EMAIL: ${{ secrets.EMAIL }}
      
      - name: Init scraper
        run: python example.py
